version: '3.5'

networks:
  backend:
    name: nexus_network

volumes:
  nexus_data:

services:

  nexus:
    image: sonatype/nexus3:${NEXUS_VERSION:-latest}
    container_name: nexus_nexus
    hostname: nexus_nexus
    restart: unless-stopped
    volumes:
      - nexus_data:/nexus-data
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    networks:
      - backend

  haproxy:
    build: haproxy
    image: nexus_haproxy
    container_name: nexus_haproxy
    hostname: nexus_haproxy
    restart: unless-stopped
    environment:
      HAPROXY_USER: ${HAPROXY_USER}
      HAPROXY_PASS: ${HAPROXY_PASS}
    ports:
      - 80:80
      - 81:81
      - 8080:8080
    depends_on:
      - nexus
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    networks:
      - backend

