version: '3'

networks:
  backend:
    name: nexus_network

volumes:
  nexus_data:

x-base: &base
  restart: unless-stopped
  logging:
    options:
      max-size: "1m"
      max-file: "10"
  networks:
    - backend

services:
  nexus:
    <<: *base
    image: sonatype/nexus3:${NEXUS_VERSION:-latest}
    container_name: nexus_nexus
    hostname: nexus_nexus
    volumes:
      - nexus_data:/nexus-data
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536

  haproxy:
    <<: *base
    build: haproxy
    container_name: nexus_haproxy
    hostname: nexus_haproxy
    environment:
      HAPROXY_USER: ${HAPROXY_USER}
      HAPROXY_PASS: ${HAPROXY_PASS}
    ports:
      - 80:80
      - 81:81
      - 8080:8080
    depends_on:
      - nexus
